package com.universal.downloader.ui.screens

import android.annotation.SuppressLint
import android.webkit.CookieManager
import android.webkit.WebResourceRequest
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Check
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import com.universal.downloader.ui.theme.PrimaryCyan
import com.universal.downloader.ui.theme.SurfaceDark

@OptIn(ExperimentalMaterial3Api::class)
@SuppressLint("SetJavaScriptEnabled")
@Composable
fun CookieLoginWebView(
    onNavigateBack: () -> Unit,
    onSaveCookies: (String) -> Unit
) {
    var currentUrl by remember { mutableStateOf("https://accounts.google.com/ServiceLogin?service=youtube") }
    var cookieCount by remember { mutableIntStateOf(0) }
    val context = LocalContext.current

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Web Account Login & Cookies") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    IconButton(onClick = {
                        val cookies = CookieManager.getInstance().getCookie("https://youtube.com") ?: ""
                        val netscapeFormat = convertCookiesToNetscape(cookies, ".youtube.com")
                        onSaveCookies(netscapeFormat)
                        onNavigateBack()
                    }) {
                        Icon(Icons.Default.Check, contentDescription = "Save Cookies", tint = PrimaryCyan)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = SurfaceDark)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
        ) {
            Surface(
                color = MaterialTheme.colorScheme.surfaceVariant,
                modifier = Modifier.fillMaxWidth()
            ) {
                Text(
                    text = "Sign in to YouTube to export authentication cookies for age-restricted or private streams. Tap checkmark when done.",
                    style = MaterialTheme.typography.bodySmall,
                    modifier = Modifier.padding(10.dp),
                    color = Color.LightGray
                )
            }

            AndroidView(
                factory = { ctx ->
                    WebView(ctx).apply {
                        settings.javaScriptEnabled = true
                        settings.domStorageEnabled = true
                        settings.userAgentString = "Mozilla/5.0 (Linux; Android 14; Mobile) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36"

                        webViewClient = object : WebViewClient() {
                            override fun shouldOverrideUrlLoading(view: WebView?, request: WebResourceRequest?): Boolean {
                                return false
                            }

                            override fun onPageFinished(view: WebView?, url: String?) {
                                super.onPageFinished(view, url)
                                val cookies = CookieManager.getInstance().getCookie(url)
                                if (!cookies.isNullOrEmpty()) {
                                    cookieCount = cookies.split(";").size
                                }
                            }
                        }
                        loadUrl(currentUrl)
                    }
                },
                modifier = Modifier.fillMaxSize()
            )
        }
    }
}

private fun convertCookiesToNetscape(rawCookies: String, domain: String): String {
    val builder = StringBuilder()
    builder.append("# Netscape HTTP Cookie File\n")
    builder.append("# Generated by Universal Downloader Android\n\n")

    val pairs = rawCookies.split(";")
    for (pair in pairs) {
        val trimmed = pair.trim()
        val eqIdx = trimmed.indexOf("=")
        if (eqIdx != -1) {
            val name = trimmed.substring(0, eqIdx).trim()
            val value = trimmed.substring(eqIdx + 1).trim()
            val expiry = System.currentTimeMillis() / 1000 + 365 * 24 * 3600
            builder.append("$domain\tTRUE\t/\tTRUE\t$expiry\t$name\t$value\n")
        }
    }
    return builder.toString()
}
